# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POI', '0002_auto_20180205_0828'),
        ('userauth', '0007_auto_20180116_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPoi',
            fields=[
                ('gispoi_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POI.GisPOI')),
                ('moderated_on', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(verbose_name=False)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.RegistrationTry')),
            ],
            bases=('POI.gispoi',),
        ),
    ]
