# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarionTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationtext', models.CharField(default='in this plase will be registration form', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Registrarion',
        ),
    ]
