# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0016_auto_20171219_0149'),
        ('userauth', '0003_registrariontry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(blank=True, max_length=100)),
                ('user_firstname', models.CharField(blank=True, max_length=100)),
                ('user_lastname', models.CharField(blank=True, max_length=100)),
                ('user_email', models.EmailField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrariontry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='registrariontry',
            name='text',
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='finished_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='otc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='o_t_c', to='OTC.OTCRegistration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='registrationform_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userauth.RegistrationForm'),
            preserve_default=False,
        ),
    ]
