# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20171226_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationtry',
            old_name='user_nickname',
            new_name='username',
        ),
    ]
