# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-02 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20180102_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationtry',
            old_name='user_email',
            new_name='email',
        ),
    ]
