# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20171219_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
