# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 07:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_auto_20180104_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationtry',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
