# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_auto_20171219_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrariontry',
            name='otc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_otc', to='OTC.OTCRegistration'),
        ),
    ]
