# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20171219_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrariontry',
            name='registrationform_ptr',
        ),
        migrations.RemoveField(
            model_name='registrariontry',
            name='registrationtext',
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='extra_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='user_email',
            field=models.EmailField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='user_firstname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='user_lastname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registrariontry',
            name='user_nickname',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
