# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_auto_20171220_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrariontry',
            name='extra_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrariontry',
            name='user_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrariontry',
            name='user_firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrariontry',
            name='user_lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrariontry',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
