# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
