# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='otc',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
