# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0004_auto_20171215_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otc',
            name='otc',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
