# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0010_auto_20171218_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='otc',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otc',
            name='otc',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
