# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0012_auto_20171219_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcbase',
            name='otc',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID code'),
        ),
    ]
