# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OTC', '0013_auto_20171219_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTCRegistration',
            fields=[
                ('otcbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='OTC.OTCBase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_otc', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('OTC.otcbase',),
        ),
        migrations.RemoveField(
            model_name='otcbase',
            name='datetime',
        ),
        migrations.AddField(
            model_name='otcbase',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created in'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otcbase',
            name='used_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='used in'),
        ),
        migrations.AlterField(
            model_name='otcbase',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='is used'),
        ),
    ]
