# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0015_otcbase_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otcbase',
            name='link',
        ),
        migrations.AddField(
            model_name='otcregistration',
            name='link',
            field=models.CharField(blank=True, max_length=256, verbose_name='link'),
        ),
    ]
