# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 04:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTC', '0017_auto_20171219_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otcregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_otc', to=settings.AUTH_USER_MODEL),
        ),
    ]
