# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='created_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='image_large',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='radius',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gispoi',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
