# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gispoi',
            name='radius',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
