# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 10:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='poi', to='POI.Category'),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='created_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cratedpoi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftgispoi',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='draftpoi', to='POI.Category'),
        ),
    ]
