# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poi',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
