# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0002_auto_20180202_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='addres',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
