# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 11:49
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('POI', '0002_auto_20180205_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
