# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0002_auto_20180129_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='create_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
