# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0003_auto_20180129_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisPOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
