# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0003_gispoi_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gispoi',
            old_name='image_large',
            new_name='image',
        ),
        migrations.AddField(
            model_name='gispoi',
            name='name',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gispoi',
            name='addres',
            field=models.TextField(null=True),
        ),
    ]
