# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0004_auto_20180202_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='extra_data',
            field=models.TextField(null=True),
        ),
    ]
