# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 12:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0004_gispoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
