# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gispoi',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='POI.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Category'),
        ),
    ]
