# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0005_auto_20180219_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('main', 'main cat'), ('1', 'cat1'), ('2', 'cat2'), ('1.1', 'sub cat1'), ('1.2', 'sub cat2'), ('2.1', 'sub_cat1'), ('2.2', 'sub_cat2')], max_length=150, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gispoi',
            name='radius',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
