# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0006_auto_20180219_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('by interaction', 'by interaction'), ('active (visit or take part in)', 'active (visit or take part in)'), ('pasive (just look)', 'pasive (just look)'), ('by type', 'by type'), ('art and culture', 'art and culture'), ('mass culture', 'mass culture'), ('historical places', 'historical places'), ('cultural heritage', 'cultural heritage'), ('architecture', 'architecture'), ('art', 'art'), ('have fun or eating', 'have fun or eating'), ('cinema', 'cinema'), ('cafe, rerestaurant, pub', 'cafe, rerestaurant, pub'), ('recreation', 'recreation'), ('religion', 'religion'), ('temples and churches', 'temples and churches'), ('places of religious worship', 'places of religious worship'), ('beautiful places', 'beautiful places'), ('landscape', 'landscape'), ('place', 'place')], max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='POI.Category'),
        ),
    ]
