# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0008_auto_20180226_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gispoi',
            name='category',
        ),
        migrations.AddField(
            model_name='gispoi',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='cat', to='POI.Category'),
        ),
    ]
