# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0009_auto_20180226_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gispoi',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cat', to='POI.Category'),
        ),
    ]
