# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0010_auto_20180227_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=25, unique=True),
        ),
    ]
