# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 10:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('POI', '0012_auto_20180227_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftGisPOI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('addres', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('create_in', models.DateTimeField(auto_now_add=True)),
                ('radius', models.PositiveIntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, related_name='cat', to='POI.Category')),
                ('created_was', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='create_in',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='created_was',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='point',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='gispoi',
            name='tags',
        ),
        migrations.AddField(
            model_name='gispoi',
            name='is_moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='moderated_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='moderation_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gispoi',
            name='draftgispoi_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='POI.DraftGisPOI'),
            preserve_default=False,
        ),
    ]
