# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-02 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POI', '0013_auto_20180302_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gispoi',
            name='is_moderate',
        ),
        migrations.AddField(
            model_name='draftgispoi',
            name='is_moderate',
            field=models.BooleanField(default=False),
        ),
    ]
